language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: "__token__"
  password:
    secure: SSQHqiPdDectgOO5mwTsIxdPhJBf86OgaHZKmghQPK+c9X5FCOkuAwzWsUrixjEaGJBPI3MaU/Yk8gzFV7aZVXvYQllQghJsgbRWJgF6wmVjIgiVrywYk6p/Sa7VLB/izO6qudgsV4Qr3IDN/zrsYYhRBUZ9eTAFGtuUy1VTICIirPS3deAvBlSMLLI4vMGDhZz1wYkm0h70xNkFTvfsDhKEo6PeSUF8ID2l9z/ok+yo8X4EAVjw81MMFv82itKfHISjvadORV91hSrnZ8W/VSmW+P96/+TFiProk8WmQOq/PwrpmW/7ehd9LT8Vrh7ifx/lFxnyuraC+lRLwKPIsqY3cfmQGrEO7WdtyMVDrEleYFUKm4Y9nI5qtUxbUndiqHr5QE1L6BMcgqhFh1vNuM82wEPZbLwGEMPwAa1M8+USLEagqy9UWAVKzdAFNg1kv4NZ/UeBmkSVQMmdhPfmDw2qjQZJGPsXD2AEQr+odzOX3o3VXdZCiMw0jl5T/QY+ZSJHb8cvzxXe7lbEmpeflbf88fpCkk6oMhckcYY1+QZhSz44tzCLRoLEBiVq5TqmvmJg6ZF7EtVdpxGYbgMLRI6EnWCTsJJeTmVWnPA92W1w0uRLkdT1bfWF9krxFYpX/hEcSyxDtgb/lBWkdNs/JCi7gpUqHuQaFweUTQwWnsQ=
  on:
    tags: true
    repo: Ledenel/fdf
    python: 3.8
