language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: "__token__"
  password:
    secure: rBOcY5MUdiWBetJ6tlnCjihjRpS4j4G1R8n5Y2atu8HI6TQV5iigbQk0zCjpOohI5tA0swRyZrr/Fsc9Pm4tRbsBV/jKM3HQdsdTRoqDDvjvwUU2yqGiV3cznogu+lA7lM9C4bMWmyJhC93VtLtr+gKvJEVMJTZ7cK+b0ayc0ZOuy2wVZ30bFItmwfJYDyUs713OnKWQkN26am6zg4txllKYj1CroNPHH1jqeqj2mAUKem5cDYHFP5com0kplYXl0FnQEB4KC6c6W4MosSZ/Ik58k37pYnfdp3cF4ytyFxzNxXGSv2J8x0wP5LyKPrexPG7CitiyGckOQiDeJn2PtM0QyFdTGlV8uhQPj6TczSgpu0rZuEyBqmq42ggilGe8ftsCPfo/kcscrN9+RdxG5r0LKRO28Zv0seuvyXU8nfucfm/Wy8YmBUlmouDOUsrKb+qpfNEneYGrFdYXnFXPhgMmtJmzu5qxz0kzJjzQHOJAL71ISd6PlF7pqDvwWuYWMDYFcg6dXi6huSZX39jEfEjkHU5gqpQ07eYpM/aZp+wUKqt3/GRr6jFNzA/M7EaWLRXHQciMM4pA49CU2UPrUJ0fZqAWbckXX44GyLokTAHfp4NnwPqgxaV+EzoWoysjKXUNS1IXQbZq2WRozKQLstqvV9PIU8Uq0LwQwvgSDhI=
  on:
    tags: true
    repo: Ledenel/fdf
    python: 3.8
