language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: SGYWIEn/AU1qsXPnv23K0WRjJ1dzK3d2wQ2T+dpCQ2oQpz3S8CeiLgEHeqlE5TKQtGmds6vvu+DDWnvMFmpoMvslnTOH6wyCXboxlLR0nciuYj+bMXrMaqqJkhJ8e4HQ78ary/xI/MiuUlJuxdXoUhnH47Mc1HRY0d6cywfLdYDUC2CSNZKMjLPhi/uxDQNa5C8vbbuA3a8k9uOxKk66UUP8KuUm/F62RF3KMu4E4p8Bf7FKc8Kac80NompX3DSfG11LcJiNqe0IGj6FT/2zwaZ7ZiG6c/lp/Ad+qjnHzXWO+ZMK1190XLY/iZ/MhSovqriiezmdy1fe4FoMx+R4QG/YZ0s+2k4M4DM9aI5vUUDpuKlIwHxLKyoxpFATP3Q1M3pvHjvIWwl4laTKjnJdEeQFCj4UssiPuZVyA7r1pCosuAJI59ffArcgrLX1e21ykqfQy3uNaPArdZepKId3ZA8bvzbFpuxmKgXAuu77IIzI3KHANh6jl3pvggLMeGw7fZRD79yhTVrkkUMtotNT8hoL2NMspullel9XMnv26Vg32/0ytdyD2sAHwrEi4TJ00k1JOBHISpPTEY397tuYJ7TxIag9y0Ge/BEJLJr9SjGVR94lc6XzkLVSBA9DK82n58Gw0cX2ZNphgTbJ8GXZwsKt+uwLKcDOaORnVJLBERc=
  on:
    tags: true
    repo: Ledenel/fdf
    python: 3.8
